# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-11-21 04:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_dishes_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='category',
            field=models.CharField(choices=[('payed', 'Payed'), ('ready', 'Ready'), ('pending', 'Pending')], default='payed', max_length=7),
            preserve_default=False,
        ),
    ]
