# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-11-23 23:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0004_auto_20171123_2351'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tables',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='tables',
            name='waiter',
        ),
        migrations.AddField(
            model_name='tables',
            name='available',
            field=models.BooleanField(default=True),
        ),
    ]
